// Code generated by mcp/scripts/generate-contracts.py; DO NOT EDIT.
package contracts

const (
	SchemaVersion = 1
	CatalogSHA256 = "6ba3fc8b12832d57feca813ea7eeed578a105c2541f5bc5898413c5752838081"
	ProductIdentity = "last30days"
	ServiceAPIMin = 1
	ServiceAPIMax = 1
	DatabaseSchemaMin = 14
	DatabaseSchemaMax = 14
)

var QueryRequestFields = []string{"filters", "freshness_policy", "max_chars", "profile_id", "query", "request_id", "response_mode", "schema_version", "top_k", "wait_ms"}
var QueryFilterFields = []string{"published_after", "published_before", "sources", "topic_ids"}
