// Code generated by mcp/scripts/generate-contracts.py; DO NOT EDIT.
package contracts

const (
	SchemaVersion = 1
	CatalogSHA256 = "ff7923059768032111fe47af144a060bb95180c90214b6a19e73ec4844a2edb6"
	ProductIdentity = "last30days"
	ServiceAPIMin = 1
	ServiceAPIMax = 1
	DatabaseSchemaMin = 18
	DatabaseSchemaMax = 18
)

var QueryRequestFields = []string{"filters", "freshness_policy", "max_chars", "profile_id", "query", "request_id", "response_mode", "schema_version", "top_k", "wait_ms"}
var QueryFilterFields = []string{"published_after", "published_before", "sources", "topic_ids"}
