// Code generated by mcp/scripts/generate-contracts.py; DO NOT EDIT.
package contracts

const (
	SchemaVersion = 1
	CatalogSHA256 = "3fb7df8ab6d17e1e381090120a7d30c99027cc3d555b1c3bfe7a0eeb84983c6f"
	ProductIdentity = "last30days"
	ServiceAPIMin = 1
	ServiceAPIMax = 1
	DatabaseSchemaMin = 12
	DatabaseSchemaMax = 12
)

var QueryRequestFields = []string{"filters", "freshness_policy", "max_chars", "profile_id", "query", "request_id", "response_mode", "schema_version", "top_k", "wait_ms"}
var QueryFilterFields = []string{"published_after", "published_before", "sources", "topic_ids"}
