#!/usr/bin/env python3
"""Generate the Go transport compatibility constants from the canonical catalog."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "skills/last30days/schemas/service-contracts-v1.json"
OUTPUT = ROOT / "mcp/internal/contracts/catalog_generated.go"


def go_strings(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def main() -> None:
    raw = CATALOG.read_bytes()
    catalog = json.loads(raw)
    query = catalog["contracts"]["query_request"]
    filters = query["properties"]["filters"]["properties"]
    content = f"""// Code generated by mcp/scripts/generate-contracts.py; DO NOT EDIT.
package contracts

const (
\tSchemaVersion = {catalog["schema_version"]}
\tCatalogSHA256 = "{hashlib.sha256(raw).hexdigest()}"
)

var QueryRequestFields = []string{{{go_strings(sorted(query["properties"]))}}}
var QueryFilterFields = []string{{{go_strings(sorted(filters))}}}
"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
